# charts/social-game/values.yaml

replicaCount: 3

image:
  repository: ahmedbenrejeb0/backend
  tag: 161591b3a0eb4fc14b5fd68563cdc35c75eceed5
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: killer-game.local