# charts/social-game/values.yaml

replicaCount: 3

image:
  repository: ahmedbenrejeb0/backend
  tag: d18d55f879f419fab5edee46d1a7159f6a1efc68
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: killer-game.local