name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'deployement/**' # Don't run if we only changed the yaml! (Prevents infinite loops)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Tag with "latest" AND the specific git commit hash (sha)
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/social-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/social-backend:${{ github.sha }}

      - name: Update Kubernetes Manifest
        run: |
          # 1. Configure Git
          git config user.name "GitHub Actions Robot"
          git config user.email "actions@github.com"

          # 2. Edit the deployment file using 'sed'
          # This replaces the image tag with the new commit hash
          sed -i "s|image: .*social-backend:.*|image: ${{ secrets.DOCKER_USERNAME }}/social-backend:${{ github.sha }}|g" deployement/backend-deployment.yaml

          # 3. Commit and Push the change back to the repo
          git add deployement/backend.yml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push